# Generated by Django 3.1.5 on 2021-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spieler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('type', models.SmallIntegerField()),
                ('room_code', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='karte',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
