# Generated by Django 3.1.5 on 2021-03-08 11:26

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210308_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karte',
            name='code',
            field=models.UUIDField(default=uuid.UUID, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='code',
            field=models.UUIDField(default=uuid.UUID, unique=True),
        ),
    ]
