# Generated by Django 3.1.5 on 2021-03-08 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210308_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='code',
            field=models.UUIDField(default=uuid.UUID('4970b7f0-a84b-44b6-873b-c7369a23ed24'), unique=True),
        ),
    ]
