# Generated by Django 3.1.5 on 2021-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210308_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='type',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
