# Generated by Django 3.1.5 on 2021-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_karte_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='karte',
            name='usedByType',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
