# Generated by Django 3.1.5 on 2021-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210314_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karte',
            name='usedByType',
        ),
        migrations.AddField(
            model_name='karte',
            name='usedByDealer',
            field=models.BooleanField(default=False),
        ),
    ]
