# Generated by Django 3.1.5 on 2021-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_karte_usedbydealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='karte',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
