# Generated by Django 3.1.5 on 2021-03-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_karte_inuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='dealerTries',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spieler',
            name='guesserTries',
            field=models.SmallIntegerField(null=True),
        ),
    ]
