# Generated by Django 3.1.5 on 2021-03-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210314_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='dealerTries',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='guesserTries',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
