# Generated by Django 3.1.5 on 2021-03-16 08:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210314_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('message', models.TextField(max_length=300, null=True)),
                ('player_code', models.CharField(max_length=8)),
                ('room_code', models.CharField(max_length=8)),
                ('seeable', models.BooleanField(default=True)),
            ],
        ),
    ]
