# Generated by Django 3.1.5 on 2021-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='canTip',
            field=models.BooleanField(default=False),
        ),
    ]
